// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgumazpqjdbrpjgiztxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNndW1henBxamRicnBqZ2l6dHh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MjY2NjYsImV4cCI6MjA3MTQwMjY2Nn0.4IuqRoP9X7GzoWa6lmWU1iEb8mESr1Vff16ZjnM5C4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});